### ISSUE TITLE
import error: run benchmark.py 

### ISSUE THREAD

**Issue by xuleyoung** [ClementPinard/Pytorch-Correlation-extension#18]
when I run 
python benchmark.py cpu

Traceback (most recent call last):
  File "benchmark.py", line 8, in <module>
    from spatial_correlation_sampler import SpatialCorrelationSampler
  File "/media/data2/xly/anaconda3/lib/python3.7/site-packages/spatial_correlation_sampler-0.1.0-py3.7-linux-x86_64.egg/spatial_correlation_sampler/__init__.py", line 1, in <module>
    from .spatial_correlation_sampler import SpatialCorrelationSampler, SpatialCorrelationSamplerFunction, spatial_correlation_sample
  File "/media/data2/xly/anaconda3/lib/python3.7/site-packages/spatial_correlation_sampler-0.1.0-py3.7-linux-x86_64.egg/spatial_correlation_sampler/spatial_correlation_sampler.py", line 6, in <module>
    import spatial_correlation_sampler_backend as correlation
ImportError: /media/data2/xly/anaconda3/lib/python3.7/site-packages/spatial_correlation_sampler-0.1.0-py3.7-linux-x86_64.egg/spatial_correlation_sampler_backend.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _Z25correlation_cuda_backwardN2at6TensorES0_S0_iiiiiiiiii

**Comment by xuleyoung** [comment]
Hi,
I modify the *.cu file.
commet
#include <torch/extension.h>
then add
#include<torch/serialize/tensor.h>
I don't why ,but it works.
thank you.
