### ISSUE TITLE
cant install correlation extension

### ISSUE THREAD

**Issue by Chao86** [ClementPinard/Pytorch-Correlation-extension#38]
hi, when install correlation extension, an error occured`Collecting spatial-correlation-sampler==0.2.0
  Downloading https://files.pythonhosted.org/packages/0e/81/37a407309ba447a7a710d74aa06bfcfed29f160862d824d76e7cdbae57c7/spatial_correlation_sampler-0.2.0.tar.gz
Requirement already satisfied: torch>=1.1 in /data/ch/anaconda3/envs/THTF/lib/python3.6/site-packages (from spatial-correlation-sampler==0.2.0) (1.1.0)
Requirement already satisfied: numpy in /data/ch/anaconda3/envs/THTF/lib/python3.6/site-packages (from spatial-correlation-sampler==0.2.0) (1.17.3)
Building wheels for collected packages: spatial-correlation-sampler
  Building wheel for spatial-correlation-sampler (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /data/ch/anaconda3/envs/THTF/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-otlptma3/spatial-correlation-sampler/setup.py'"'"'; __file__='"'"'/tmp/pip-install-otlptma3/spatial-correlation-sampler/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-m0g5tnqy --python-tag cp36
       cwd: /tmp/pip-install-otlptma3/spatial-correlation-sampler/
  Complete output (52 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  creating build/lib.linux-x86_64-3.6/spatial_correlation_sampler
  copying Correlation_Module/spatial_correlation_sampler/spatial_correlation_sampler.py -> build/lib.linux-x86_64-3.6/spatial_correlation_sampler
  copying Correlation_Module/spatial_correlation_sampler/__init__.py -> build/lib.linux-x86_64-3.6/spatial_correlation_sampler
  running build_ext
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-otlptma3/spatial-correlation-sampler/setup.py", line 57, in <module>
      launch_setup()
    File "/tmp/pip-install-otlptma3/spatial-correlation-sampler/setup.py", line 52, in launch_setup
      "Topic :: Scientific/Engineering :: Artificial Intelligence"
    File "/data/ch/anaconda3/envs/THTF/lib/python3.6/site-packages/setuptools/__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "/data/ch/anaconda3/envs/THTF/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/data/ch/anaconda3/envs/THTF/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/data/ch/anaconda3/envs/THTF/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/data/ch/anaconda3/envs/THTF/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 192, in run
      self.run_command('build')
    File "/data/ch/anaconda3/envs/THTF/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/data/ch/anaconda3/envs/THTF/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/data/ch/anaconda3/envs/THTF/lib/python3.6/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/data/ch/anaconda3/envs/THTF/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/data/ch/anaconda3/envs/THTF/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/data/ch/anaconda3/envs/THTF/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 84, in run
      _build_ext.run(self)
    File "/data/ch/anaconda3/envs/THTF/lib/python3.6/distutils/command/build_ext.py", line 339, in run
      self.build_extensions()
    File "/data/ch/anaconda3/envs/THTF/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 232, in build_extensions
      self._check_abi()
    File "/data/ch/anaconda3/envs/THTF/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 370, in _check_abi
      check_compiler_abi_compatibility(compiler)
    File "/data/ch/anaconda3/envs/THTF/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 162, in check_compiler_abi_compatibility
      if not check_compiler_ok_for_platform(compiler):
    File "/data/ch/anaconda3/envs/THTF/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 138, in check_compiler_ok_for_platform
      which = subprocess.check_output(['which', compiler], stderr=subprocess.STDOUT)
    File "/data/ch/anaconda3/envs/THTF/lib/python3.6/subprocess.py", line 356, in check_output
      **kwargs).stdout
    File "/data/ch/anaconda3/envs/THTF/lib/python3.6/subprocess.py", line 438, in run
      output=stdout, stderr=stderr)
  subprocess.CalledProcessError: Command '['which', '/path/to/gcc-5.4.0//bin/g++']' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for spatial-correlation-sampler
  Running setup.py clean for spatial-correlation-sampler
Failed to build spatial-correlation-sampler
Installing collected packages: spatial-correlation-sampler
    Running setup.py install for spatial-correlation-sampler ... error
    ERROR: Command errored out with exit status 1:
     command: /data/ch/anaconda3/envs/THTF/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-otlptma3/spatial-correlation-sampler/setup.py'"'"'; __file__='"'"'/tmp/pip-install-otlptma3/spatial-correlation-sampler/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-fv2lxtb3/install-record.txt --single-version-externally-managed --compile
         cwd: /tmp/pip-install-otlptma3/spatial-correlation-sampler/
    Complete output (54 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/spatial_correlation_sampler
    copying Correlation_Module/spatial_correlation_sampler/spatial_correlation_sampler.py -> build/lib.linux-x86_64-3.6/spatial_correlation_sampler
    copying Correlation_Module/spatial_correlation_sampler/__init__.py -> build/lib.linux-x86_64-3.6/spatial_correlation_sampler
    running build_ext
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-otlptma3/spatial-correlation-sampler/setup.py", line 57, in <module>
        launch_setup()
      File "/tmp/pip-install-otlptma3/spatial-correlation-sampler/setup.py", line 52, in launch_setup
        "Topic :: Scientific/Engineering :: Artificial Intelligence"
      File "/data/ch/anaconda3/envs/THTF/lib/python3.6/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/data/ch/anaconda3/envs/THTF/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/data/ch/anaconda3/envs/THTF/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/data/ch/anaconda3/envs/THTF/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/data/ch/anaconda3/envs/THTF/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/data/ch/anaconda3/envs/THTF/lib/python3.6/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/data/ch/anaconda3/envs/THTF/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/data/ch/anaconda3/envs/THTF/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/data/ch/anaconda3/envs/THTF/lib/python3.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/data/ch/anaconda3/envs/THTF/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/data/ch/anaconda3/envs/THTF/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/data/ch/anaconda3/envs/THTF/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 84, in run
        _build_ext.run(self)
      File "/data/ch/anaconda3/envs/THTF/lib/python3.6/distutils/command/build_ext.py", line 339, in run
        self.build_extensions()
      File "/data/ch/anaconda3/envs/THTF/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 232, in build_extensions
        self._check_abi()
      File "/data/ch/anaconda3/envs/THTF/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 370, in _check_abi
        check_compiler_abi_compatibility(compiler)
      File "/data/ch/anaconda3/envs/THTF/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 162, in check_compiler_abi_compatibility
        if not check_compiler_ok_for_platform(compiler):
      File "/data/ch/anaconda3/envs/THTF/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 138, in check_compiler_ok_for_platform
        which = subprocess.check_output(['which', compiler], stderr=subprocess.STDOUT)
      File "/data/ch/anaconda3/envs/THTF/lib/python3.6/subprocess.py", line 356, in check_output
        **kwargs).stdout
      File "/data/ch/anaconda3/envs/THTF/lib/python3.6/subprocess.py", line 438, in run
        output=stdout, stderr=stderr)
    subprocess.CalledProcessError: Command '['which', '/path/to/gcc-5.4.0//bin/g++']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /data/ch/anaconda3/envs/THTF/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-otlptma3/spatial-correlation-sampler/setup.py'"'"'; __file__='"'"'/tmp/pip-install-otlptma3/spatial-correlation-sampler/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-fv2lxtb3/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.
`
my enviroment is python->3.6
cuda->9.0
gcc->5.0
torch->1.0
i don't know how to handle please help me, Thank you

**Comment by ClementPinard** [comment]
Seems like you have a problem with finding the right g++
Can you try to install it from this repo directly instead ?
clone the repo and launch `python setup.py install`
