### ISSUE TITLE
 cant installspatial-correlation-sampler

### ISSUE THREAD

**Issue by shanchao0906** [ClementPinard/Pytorch-Correlation-extension#48]
I'm sorry to have bothered you
I first downloaded your code package：Pytorch Correlation- Extension，
Unzip it and place it in the Lib -Sitepackages directory under the Python path
Enter Python setup.py install after the corresponding path under the CMD window
The following is my error report. I tried many ways but still couldn't install it
python3.7 torch1.6 cuda 10.2 gcc9.3 
##############
C:\Python38\Lib\site-packages\Pytorch-Correlation-extension>python setup.py install
running install
running bdist_egg
running egg_info
creating Correlation_Module\spatial_correlation_sampler.egg-info
writing Correlation_Module\spatial_correlation_sampler.egg-info\PKG-INFO
writing dependency_links to Correlation_Module\spatial_correlation_sampler.egg-info\dependency_links.txt
writing requirements to Correlation_Module\spatial_correlation_sampler.egg-info\requires.txt
writing top-level names to Correlation_Module\spatial_correlation_sampler.egg-info\top_level.txt
writing manifest file 'Correlation_Module\spatial_correlation_sampler.egg-info\SOURCES.txt'
reading manifest file 'Correlation_Module\spatial_correlation_sampler.egg-info\SOURCES.txt'
writing manifest file 'Correlation_Module\spatial_correlation_sampler.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
creating build
creating build\lib.win-amd64-3.7
creating build\lib.win-amd64-3.7\spatial_correlation_sampler
copying Correlation_Module\spatial_correlation_sampler\spatial_correlation_sampler.py -> build\lib.win-amd64-3.7\spatial_correlation_sampler
copying Correlation_Module\spatial_correlation_sampler\__init__.py -> build\lib.win-amd64-3.7\spatial_correlation_sampler
running build_ext
D:\workshop\lib\site-packages\torch\utils\cpp_extension.py:270: UserWarning: Error checking compiler version for cl: Command 'cl' returned non-zero exit status 1.
  warnings.warn('Error checking compiler version for {}: {}'.format(compiler, error))
building 'spatial_correlation_sampler_backend' extension
creating C:\Python38\Lib\site-packages\Pytorch-Correlation-extension\build\temp.win-amd64-3.7
creating C:\Python38\Lib\site-packages\Pytorch-Correlation-extension\build\temp.win-amd64-3.7\Release
creating C:\Python38\Lib\site-packages\Pytorch-Correlation-extension\build\temp.win-amd64-3.7\Release\Correlation_ModuleEmitting ninja build file C:\Python38\Lib\site-packages\Pytorch-Correlation-extension\build\temp.win-amd64-3.7\Release\build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/3] cl /showIncludes /nologo /Ox /W3 /GL /DNDEBUG /MD /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /EHsc -DUSE_CUDA -ID:\workshop\lib\site-packages\torch\include -ID:\workshop\lib\site-packages\torch\include\torch\csrc\api\include -ID:\workshop\lib\site-packages\torch\include\TH -ID:\workshop\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\include" -ID:\workshop\include -ID:\workshop\include -c C:\Python38\Lib\site-packages\Pytorch-Correlation-extension\Correlation_Module\correlation.cpp /FoC:\Python38\Lib\site-packages\Pytorch-Correlation-extension\build\temp.win-amd64-3.7\Release\Correlation_Module\correlation.obj -fopenmp -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=spatial_correlation_sampler_backend -D_GLIBCXX_USE_CXX11_ABI=0 /std:c++14
FAILED: C:/Python38/Lib/site-packages/Pytorch-Correlation-extension/build/temp.win-amd64-3.7/Release/Correlation_Module/correlation.obj
cl /showIncludes /nologo /Ox /W3 /GL /DNDEBUG /MD /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /EHsc -DUSE_CUDA -ID:\workshop\lib\site-packages\torch\include -ID:\workshop\lib\site-packages\torch\include\torch\csrc\api\include -ID:\workshop\lib\site-packages\torch\include\TH -ID:\workshop\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\include" -ID:\workshop\include -ID:\workshop\include -c C:\Python38\Lib\site-packages\Pytorch-Correlation-extension\Correlation_Module\correlation.cpp /FoC:\Python38\Lib\site-packages\Pytorch-Correlation-extension\build\temp.win-amd64-3.7\Release\Correlation_Module\correlation.obj -fopenmp -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=spatial_correlation_sampler_backend -D_GLIBCXX_USE_CXX11_ABI=0 /std:c++14
CreateProcess failed: The system cannot find the file specified.
[2/3] cl /showIncludes /nologo /Ox /W3 /GL /DNDEBUG /MD /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /EHsc -DUSE_CUDA -ID:\workshop\lib\site-packages\torch\include -ID:\workshop\lib\site-packages\torch\include\torch\csrc\api\include -ID:\workshop\lib\site-packages\torch\include\TH -ID:\workshop\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\include" -ID:\workshop\include -ID:\workshop\include -c C:\Python38\Lib\site-packages\Pytorch-Correlation-extension\Correlation_Module\correlation_sampler.cpp /FoC:\Python38\Lib\site-packages\Pytorch-Correlation-extension\build\temp.win-amd64-3.7\Release\Correlation_Module\correlation_sampler.obj -fopenmp -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=spatial_correlation_sampler_backend -D_GLIBCXX_USE_CXX11_ABI=0 /std:c++14
FAILED: C:/Python38/Lib/site-packages/Pytorch-Correlation-extension/build/temp.win-amd64-3.7/Release/Correlation_Module/correlation_sampler.obj
cl /showIncludes /nologo /Ox /W3 /GL /DNDEBUG /MD /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /EHsc -DUSE_CUDA -ID:\workshop\lib\site-packages\torch\include -ID:\workshop\lib\site-packages\torch\include\torch\csrc\api\include -ID:\workshop\lib\site-packages\torch\include\TH -ID:\workshop\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\include" -ID:\workshop\include -ID:\workshop\include -c C:\Python38\Lib\site-packages\Pytorch-Correlation-extension\Correlation_Module\correlation_sampler.cpp /FoC:\Python38\Lib\site-packages\Pytorch-Correlation-extension\build\temp.win-amd64-3.7\Release\Correlation_Module\correlation_sampler.obj -fopenmp -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=spatial_correlation_sampler_backend -D_GLIBCXX_USE_CXX11_ABI=0 /std:c++14
CreateProcess failed: The system cannot find the file specified.
ninja: fatal: ReadFile: 句柄无效。

Traceback (most recent call last):
  File "D:\workshop\lib\site-packages\torch\utils\cpp_extension.py", line 1515, in _run_ninja_build
    env=env)
  File "D:\workshop\lib\subprocess.py", line 468, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 57, in <module>
    launch_setup()
  File "setup.py", line 52, in launch_setup
    "Topic :: Scientific/Engineering :: Artificial Intelligence"
  File "D:\workshop\lib\site-packages\setuptools\__init__.py", line 165, in setup
    return distutils.core.setup(**attrs)
  File "D:\workshop\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "D:\workshop\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "D:\workshop\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "D:\workshop\lib\site-packages\setuptools\command\install.py", line 67, in run
    self.do_egg_install()
  File "D:\workshop\lib\site-packages\setuptools\command\install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "D:\workshop\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "D:\workshop\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "D:\workshop\lib\site-packages\setuptools\command\bdist_egg.py", line 174, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "D:\workshop\lib\site-packages\setuptools\command\bdist_egg.py", line 160, in call_command
    self.run_command(cmdname)
  File "D:\workshop\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "D:\workshop\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "D:\workshop\lib\site-packages\setuptools\command\install_lib.py", line 11, in run
    self.build()
  File "D:\workshop\lib\distutils\command\install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "D:\workshop\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "D:\workshop\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "D:\workshop\lib\site-packages\setuptools\command\build_ext.py", line 87, in run
    _build_ext.run(self)
  File "D:\workshop\lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "D:\workshop\lib\distutils\command\build_ext.py", line 339, in run
    self.build_extensions()
  File "D:\workshop\lib\site-packages\torch\utils\cpp_extension.py", line 649, in build_extensions
    build_ext.build_extensions(self)
  File "D:\workshop\lib\site-packages\Cython\Distutils\old_build_ext.py", line 194, in build_extensions
    self.build_extension(ext)
  File "D:\workshop\lib\site-packages\setuptools\command\build_ext.py", line 208, in build_extension
    _build_ext.build_extension(self, ext)
  File "D:\workshop\lib\distutils\command\build_ext.py", line 533, in build_extension
    depends=ext.depends)
  File "D:\workshop\lib\site-packages\torch\utils\cpp_extension.py", line 631, in win_wrap_ninja_compile
    with_cuda=with_cuda)
  File "D:\workshop\lib\site-packages\torch\utils\cpp_extension.py", line 1233, in _write_ninja_file_and_compile_objects    error_prefix='Error compiling objects for extension')
  File "D:\workshop\lib\site-packages\torch\utils\cpp_extension.py", line 1529, in _run_ninja_build
    raise RuntimeError(message)
RuntimeError: Error compiling objects for extension
#####################

**Comment by ClementPinard** [comment]
You don't need to unzip it in the site-packages folder. Normally it's the setup.py job to do so.

Other than that, I'll have some difficulty helping you since I don't have windows ...
Best advice is to try the official extension-cpp example and post related problems there.

**Comment by ClementPinard** [comment]
Had some difficulties recently, and that was because ninja was not installed on my environment, is it the case for you ?

**Comment by shanchao0906** [comment]
Thank you very much for your answer
However, Due to the time I am mainly running Flownets, FlownetC has not had a chance to try this out
In the literature, Flownets USES 1 by 1 convolution, but it is not included in your code
Is that right? Thank you very much

**Comment by shanchao0906** [comment]
Flownetc is also running successfully. I think it was an error during installation. The code is basically running and ready for further modification based on your experience.Thank you very much for your contribution
