### ISSUE TITLE
Install errors with pytorh=1.6.0

### ISSUE THREAD

**Issue by chenfsjz** [ClementPinard/Pytorch-Correlation-extension#71]
Hi, my env is:
 
    python                 3.7
    pytorch                1.6.0           
    cudatoolkit          10.2.89            
    torchvision           0.7.0

 When I install the pytorch-Correlation-extension with pip, there are following errors:
  
    Requirement already satisfied: torch>=1.1 in ./lib/python3.7/site-packages (from spatial-correlation-sampler) (1.6.0)
      Requirement already satisfied: numpy in ./lib/python3.7/site-packages (from spatial-correlation-sampler) (1.20.1)
      Requirement already satisfied: future in ./lib/python3.7/site-packages (from torch>=1.1->spatial-correlation-sampler) (0.18.2)
      Building wheels for collected packages: spatial-correlation-sampler
        Building wheel for spatial-correlation-sampler (setup.py) ... error
        ERROR: Command errored out with exit status 1:
         command: /home/cf-xingdao/miniconda3/envs/pytracking/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-stebrlfk/spatial-correlation-sampler_b2c1ac47bfa04681a58bc79db14418ec/setup.py'"'"'; __file__='"'"'/tmp/pip-install-stebrlfk/spatial-correlation-sampler_b2c1ac47bfa04681a58bc79db14418ec/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-w7hm80rv
             cwd: /tmp/pip-install-stebrlfk/spatial-correlation-sampler_b2c1ac47bfa04681a58bc79db14418ec/
        Complete output (84 lines):
        running bdist_wheel
        running build
        running build_py
        creating build
        creating build/lib.linux-x86_64-3.7
        creating build/lib.linux-x86_64-3.7/spatial_correlation_sampler
        copying Correlation_Module/spatial_correlation_sampler/spatial_correlation_sampler.py -> build/lib.linux-x86_64-3.7/spatial_correlation_sampler
        copying Correlation_Module/spatial_correlation_sampler/__init__.py -> build/lib.linux-x86_64-3.7/spatial_correlation_sampler
        running build_ext
        building 'spatial_correlation_sampler_backend' extension
        creating /tmp/pip-install-stebrlfk/spatial-correlation-sampler_b2c1ac47bfa04681a58bc79db14418ec/build/temp.linux-x86_64-3.7
        creating /tmp/pip-install-stebrlfk/spatial-correlation-sampler_b2c1ac47bfa04681a58bc79db14418ec/build/temp.linux-x86_64-3.7/Correlation_Module
        Emitting ninja build file /tmp/pip-install-stebrlfk/spatial-correlation-sampler_b2c1ac47bfa04681a58bc79db14418ec/build/temp.linux-x86_64-3.7/build.ninja...
        Compiling objects...
        Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
        [1/3] /usr/local/cuda/bin/nvcc -DUSE_CUDA -I/home/cf-xingdao/miniconda3/envs/pytracking/lib/python3.7/site-packages/torch/include -I/home/cf-xingdao/miniconda3/envs/pytracking/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/cf-xingdao/miniconda3/envs/pytracking/lib/python3.7/site-packages/torch/include/TH -I/home/cf-xingdao/miniconda3/envs/pytracking/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/cf-xingdao/miniconda3/envs/pytracking/include/python3.7m -c -c /tmp/pip-install-stebrlfk/spatial-correlation-sampler_b2c1ac47bfa04681a58bc79db14418ec/Correlation_Module/correlation_cuda_kernel.cu -o /tmp/pip-install-stebrlfk/spatial-correlation-sampler_b2c1ac47bfa04681a58bc79db14418ec/build/temp.linux-x86_64-3.7/Correlation_Module/correlation_cuda_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=spatial_correlation_sampler_backend -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_61,code=sm_61 -std=c++14
        FAILED: /tmp/pip-install-stebrlfk/spatial-correlation-sampler_b2c1ac47bfa04681a58bc79db14418ec/build/temp.linux-x86_64-3.7/Correlation_Module/correlation_cuda_kernel.o
        /usr/local/cuda/bin/nvcc -DUSE_CUDA -I/home/cf-xingdao/miniconda3/envs/pytracking/lib/python3.7/site-packages/torch/include -I/home/cf-xingdao/miniconda3/envs/pytracking/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/cf-xingdao/miniconda3/envs/pytracking/lib/python3.7/site-packages/torch/include/TH -I/home/cf-xingdao/miniconda3/envs/pytracking/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/cf-xingdao/miniconda3/envs/pytracking/include/python3.7m -c -c /tmp/pip-install-stebrlfk/spatial-correlation-sampler_b2c1ac47bfa04681a58bc79db14418ec/Correlation_Module/correlation_cuda_kernel.cu -o /tmp/pip-install-stebrlfk/spatial-correlation-sampler_b2c1ac47bfa04681a58bc79db14418ec/build/temp.linux-x86_64-3.7/Correlation_Module/correlation_cuda_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=spatial_correlation_sampler_backend -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_61,code=sm_61 -std=c++14
        nvcc fatal   : Value 'c++14' is not defined for option 'std'
        [2/3] c++ -MMD -MF /tmp/pip-install-stebrlfk/spatial-correlation-sampler_b2c1ac47bfa04681a58bc79db14418ec/build/temp.linux-x86_64-3.7/Correlation_Module/correlation.o.d -pthread -B /home/cf-xingdao/miniconda3/envs/pytracking/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DUSE_CUDA -I/home/cf-xingdao/miniconda3/envs/pytracking/lib/python3.7/site-packages/torch/include -I/home/cf-xingdao/miniconda3/envs/pytracking/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/cf-xingdao/miniconda3/envs/pytracking/lib/python3.7/site-packages/torch/include/TH -I/home/cf-xingdao/miniconda3/envs/pytracking/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/cf-xingdao/miniconda3/envs/pytracking/include/python3.7m -c -c /tmp/pip-install-stebrlfk/spatial-correlation-sampler_b2c1ac47bfa04681a58bc79db14418ec/Correlation_Module/correlation.cpp -o /tmp/pip-install-stebrlfk/spatial-correlation-sampler_b2c1ac47bfa04681a58bc79db14418ec/build/temp.linux-x86_64-3.7/Correlation_Module/correlation.o -fopenmp -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=spatial_correlation_sampler_backend -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
        cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
        [3/3] c++ -MMD -MF /tmp/pip-install-stebrlfk/spatial-correlation-sampler_b2c1ac47bfa04681a58bc79db14418ec/build/temp.linux-x86_64-3.7/Correlation_Module/correlation_sampler.o.d -pthread -B /home/cf-xingdao/miniconda3/envs/pytracking/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DUSE_CUDA -I/home/cf-xingdao/miniconda3/envs/pytracking/lib/python3.7/site-packages/torch/include -I/home/cf-xingdao/miniconda3/envs/pytracking/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/cf-xingdao/miniconda3/envs/pytracking/lib/python3.7/site-packages/torch/include/TH -I/home/cf-xingdao/miniconda3/envs/pytracking/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/cf-xingdao/miniconda3/envs/pytracking/include/python3.7m -c -c /tmp/pip-install-stebrlfk/spatial-correlation-sampler_b2c1ac47bfa04681a58bc79db14418ec/Correlation_Module/correlation_sampler.cpp -o /tmp/pip-install-stebrlfk/spatial-correlation-sampler_b2c1ac47bfa04681a58bc79db14418ec/build/temp.linux-x86_64-3.7/Correlation_Module/correlation_sampler.o -fopenmp -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=spatial_correlation_sampler_backend -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
        cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
        ninja: build stopped: subcommand failed.
        Traceback (most recent call last):
          File "/home/cf-xingdao/miniconda3/envs/pytracking/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1515, in _run_ninja_build
            env=env)
          File "/home/cf-xingdao/miniconda3/envs/pytracking/lib/python3.7/subprocess.py", line 512, in run
            output=stdout, stderr=stderr)
        subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
        
        During handling of the above exception, another exception occurred:
        
        Traceback (most recent call last):
          File "<string>", line 1, in <module>
          File "/tmp/pip-install-stebrlfk/spatial-correlation-sampler_b2c1ac47bfa04681a58bc79db14418ec/setup.py", line 57, in <module>
            launch_setup()
          File "/tmp/pip-install-stebrlfk/spatial-correlation-sampler_b2c1ac47bfa04681a58bc79db14418ec/setup.py", line 52, in launch_setup
            "Topic :: Scientific/Engineering :: Artificial Intelligence"
          File "/home/cf-xingdao/miniconda3/envs/pytracking/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
            return distutils.core.setup(**attrs)
          File "/home/cf-xingdao/miniconda3/envs/pytracking/lib/python3.7/distutils/core.py", line 148, in setup
            dist.run_commands()
          File "/home/cf-xingdao/miniconda3/envs/pytracking/lib/python3.7/distutils/dist.py", line 966, in run_commands
            self.run_command(cmd)
          File "/home/cf-xingdao/miniconda3/envs/pytracking/lib/python3.7/distutils/dist.py", line 985, in run_command
            cmd_obj.run()
          File "/home/cf-xingdao/miniconda3/envs/pytracking/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 299, in run
            self.run_command('build')
          File "/home/cf-xingdao/miniconda3/envs/pytracking/lib/python3.7/distutils/cmd.py", line 313, in run_command
            self.distribution.run_command(command)
          File "/home/cf-xingdao/miniconda3/envs/pytracking/lib/python3.7/distutils/dist.py", line 985, in run_command
            cmd_obj.run()
          File "/home/cf-xingdao/miniconda3/envs/pytracking/lib/python3.7/distutils/command/build.py", line 135, in run
            self.run_command(cmd_name)
          File "/home/cf-xingdao/miniconda3/envs/pytracking/lib/python3.7/distutils/cmd.py", line 313, in run_command
            self.distribution.run_command(command)
          File "/home/cf-xingdao/miniconda3/envs/pytracking/lib/python3.7/distutils/dist.py", line 985, in run_command
            cmd_obj.run()
          File "/home/cf-xingdao/miniconda3/envs/pytracking/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 79, in run
            _build_ext.run(self)
          File "/home/cf-xingdao/miniconda3/envs/pytracking/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
            _build_ext.build_ext.run(self)
          File "/home/cf-xingdao/miniconda3/envs/pytracking/lib/python3.7/distutils/command/build_ext.py", line 340, in run
            self.build_extensions()
          File "/home/cf-xingdao/miniconda3/envs/pytracking/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 649, in build_extensions
            build_ext.build_extensions(self)
          File "/home/cf-xingdao/miniconda3/envs/pytracking/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
            _build_ext.build_ext.build_extensions(self)
          File "/home/cf-xingdao/miniconda3/envs/pytracking/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
            self._build_extensions_serial()
          File "/home/cf-xingdao/miniconda3/envs/pytracking/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
            self.build_extension(ext)
          File "/home/cf-xingdao/miniconda3/envs/pytracking/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 196, in build_extension
            _build_ext.build_extension(self, ext)
          File "/home/cf-xingdao/miniconda3/envs/pytracking/lib/python3.7/distutils/command/build_ext.py", line 534, in build_extension
            depends=ext.depends)
          File "/home/cf-xingdao/miniconda3/envs/pytracking/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 478, in unix_wrap_ninja_compile
            with_cuda=with_cuda)
          File "/home/cf-xingdao/miniconda3/envs/pytracking/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1233, in _write_ninja_file_and_compile_objects
            error_prefix='Error compiling objects for extension')
          File "/home/cf-xingdao/miniconda3/envs/pytracking/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1529, in _run_ninja_build
            raise RuntimeError(message)
        RuntimeError: Error compiling objects for extension
        ----------------------------------------
        ERROR: Failed building wheel for spatial-correlation-sampler

Fom the error messages, the second message shows that:
    
    nvcc fatal   : Value 'c++14' is not defined for option 'std'

I need the help to solve this problem?

**Comment by ClementPinard** [comment]
Hi,
see this issue : https://github.com/pytorch/pytorch/issues/32135
What cuda version are you using ? Also make sure that your nvcc is the right one, the mistake can happen when multiple cuda version are installed on a computer

**Comment by chenfsjz** [comment]
Thank you for your reply! My previous cuda version is cuda-8.0. I change the cuda  version to cuda-10.1 and it works.

**Comment by ClementPinard** [comment]
Glad i could help !
