### ISSUE TITLE
i failed to install  spatial-correlation-sampler

### ISSUE THREAD

**Issue by SkyBroY** [ClementPinard/Pytorch-Correlation-extension#76]
the error message is as follows:
Building wheel for spatial-correlation-sampler (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/tianzhao.yang/anaconda3/envs/STTNet/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-_1muc1b3/spatial-correlation-sampler_916c2ab1b8b24d7aa4d9ad93b9806d2d/setup.py'"'"'; __file__='"'"'/tmp/pip-install-_1muc1b3/spatial-correlation-sampler_916c2ab1b8b24d7aa4d9ad93b9806d2d/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-224vqgsx
       cwd: /tmp/pip-install-_1muc1b3/spatial-correlation-sampler_916c2ab1b8b24d7aa4d9ad93b9806d2d/
  Complete output (80 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  creating build/lib.linux-x86_64-3.6/spatial_correlation_sampler
  copying Correlation_Module/spatial_correlation_sampler/__init__.py -> build/lib.linux-x86_64-3.6/spatial_correlation_sampler
  copying Correlation_Module/spatial_correlation_sampler/spatial_correlation_sampler.py -> build/lib.linux-x86_64-3.6/spatial_correlation_sampler
  running build_ext
  building 'spatial_correlation_sampler_backend' extension
  creating /tmp/pip-install-_1muc1b3/spatial-correlation-sampler_916c2ab1b8b24d7aa4d9ad93b9806d2d/build/temp.linux-x86_64-3.6
  creating /tmp/pip-install-_1muc1b3/spatial-correlation-sampler_916c2ab1b8b24d7aa4d9ad93b9806d2d/build/temp.linux-x86_64-3.6/Correlation_Module
  Emitting ninja build file /tmp/pip-install-_1muc1b3/spatial-correlation-sampler_916c2ab1b8b24d7aa4d9ad93b9806d2d/build/temp.linux-x86_64-3.6/build.ninja...
  Compiling objects...
  Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
  [1/3] /usr/bin/nvcc -DUSE_CUDA -I/home/tianzhao.yang/anaconda3/envs/STTNet/lib/python3.6/site-packages/torch/include -I/home/tianzhao.yang/anaconda3/envs/STTNet/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/tianzhao.yang/anaconda3/envs/STTNet/lib/python3.6/site-packages/torch/include/TH -I/home/tianzhao.yang/anaconda3/envs/STTNet/lib/python3.6/site-packages/torch/include/THC -I/home/tianzhao.yang/anaconda3/envs/STTNet/include/python3.6m -c -c /tmp/pip-install-_1muc1b3/spatial-correlation-sampler_916c2ab1b8b24d7aa4d9ad93b9806d2d/Correlation_Module/correlation_cuda_kernel.cu -o /tmp/pip-install-_1muc1b3/spatial-correlation-sampler_916c2ab1b8b24d7aa4d9ad93b9806d2d/build/temp.linux-x86_64-3.6/Correlation_Module/correlation_cuda_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=spatial_correlation_sampler_backend -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=sm_75 -std=c++14
  FAILED: /tmp/pip-install-_1muc1b3/spatial-correlation-sampler_916c2ab1b8b24d7aa4d9ad93b9806d2d/build/temp.linux-x86_64-3.6/Correlation_Module/correlation_cuda_kernel.o
  /usr/bin/nvcc -DUSE_CUDA -I/home/tianzhao.yang/anaconda3/envs/STTNet/lib/python3.6/site-packages/torch/include -I/home/tianzhao.yang/anaconda3/envs/STTNet/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/tianzhao.yang/anaconda3/envs/STTNet/lib/python3.6/site-packages/torch/include/TH -I/home/tianzhao.yang/anaconda3/envs/STTNet/lib/python3.6/site-packages/torch/include/THC -I/home/tianzhao.yang/anaconda3/envs/STTNet/include/python3.6m -c -c /tmp/pip-install-_1muc1b3/spatial-correlation-sampler_916c2ab1b8b24d7aa4d9ad93b9806d2d/Correlation_Module/correlation_cuda_kernel.cu -o /tmp/pip-install-_1muc1b3/spatial-correlation-sampler_916c2ab1b8b24d7aa4d9ad93b9806d2d/build/temp.linux-x86_64-3.6/Correlation_Module/correlation_cuda_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=spatial_correlation_sampler_backend -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=sm_75 -std=c++14
  nvcc fatal   : Unsupported gpu architecture 'compute_75'
  [2/3] c++ -MMD -MF /tmp/pip-install-_1muc1b3/spatial-correlation-sampler_916c2ab1b8b24d7aa4d9ad93b9806d2d/build/temp.linux-x86_64-3.6/Correlation_Module/correlation.o.d -pthread -B /home/tianzhao.yang/anaconda3/envs/STTNet/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DUSE_CUDA -I/home/tianzhao.yang/anaconda3/envs/STTNet/lib/python3.6/site-packages/torch/include -I/home/tianzhao.yang/anaconda3/envs/STTNet/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/tianzhao.yang/anaconda3/envs/STTNet/lib/python3.6/site-packages/torch/include/TH -I/home/tianzhao.yang/anaconda3/envs/STTNet/lib/python3.6/site-packages/torch/include/THC -I/home/tianzhao.yang/anaconda3/envs/STTNet/include/python3.6m -c -c /tmp/pip-install-_1muc1b3/spatial-correlation-sampler_916c2ab1b8b24d7aa4d9ad93b9806d2d/Correlation_Module/correlation.cpp -o /tmp/pip-install-_1muc1b3/spatial-correlation-sampler_916c2ab1b8b24d7aa4d9ad93b9806d2d/build/temp.linux-x86_64-3.6/Correlation_Module/correlation.o -fopenmp -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=spatial_correlation_sampler_backend -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
  [3/3] c++ -MMD -MF /tmp/pip-install-_1muc1b3/spatial-correlation-sampler_916c2ab1b8b24d7aa4d9ad93b9806d2d/build/temp.linux-x86_64-3.6/Correlation_Module/correlation_sampler.o.d -pthread -B /home/tianzhao.yang/anaconda3/envs/STTNet/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DUSE_CUDA -I/home/tianzhao.yang/anaconda3/envs/STTNet/lib/python3.6/site-packages/torch/include -I/home/tianzhao.yang/anaconda3/envs/STTNet/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/tianzhao.yang/anaconda3/envs/STTNet/lib/python3.6/site-packages/torch/include/TH -I/home/tianzhao.yang/anaconda3/envs/STTNet/lib/python3.6/site-packages/torch/include/THC -I/home/tianzhao.yang/anaconda3/envs/STTNet/include/python3.6m -c -c /tmp/pip-install-_1muc1b3/spatial-correlation-sampler_916c2ab1b8b24d7aa4d9ad93b9806d2d/Correlation_Module/correlation_sampler.cpp -o /tmp/pip-install-_1muc1b3/spatial-correlation-sampler_916c2ab1b8b24d7aa4d9ad93b9806d2d/build/temp.linux-x86_64-3.6/Correlation_Module/correlation_sampler.o -fopenmp -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=spatial_correlation_sampler_backend -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
  ninja: build stopped: subcommand failed.
  Traceback (most recent call last):
    File "/home/tianzhao.yang/anaconda3/envs/STTNet/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1515, in _run_ninja_build
      env=env)
    File "/home/tianzhao.yang/anaconda3/envs/STTNet/lib/python3.6/subprocess.py", line 438, in run
      output=stdout, stderr=stderr)
  subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-_1muc1b3/spatial-correlation-sampler_916c2ab1b8b24d7aa4d9ad93b9806d2d/setup.py", line 57, in <module>
      launch_setup()
    File "/tmp/pip-install-_1muc1b3/spatial-correlation-sampler_916c2ab1b8b24d7aa4d9ad93b9806d2d/setup.py", line 52, in launch_setup
      "Topic :: Scientific/Engineering :: Artificial Intelligence"
    File "/home/tianzhao.yang/anaconda3/envs/STTNet/lib/python3.6/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/home/tianzhao.yang/anaconda3/envs/STTNet/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/home/tianzhao.yang/anaconda3/envs/STTNet/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/home/tianzhao.yang/anaconda3/envs/STTNet/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/home/tianzhao.yang/anaconda3/envs/STTNet/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/home/tianzhao.yang/anaconda3/envs/STTNet/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/tianzhao.yang/anaconda3/envs/STTNet/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/home/tianzhao.yang/anaconda3/envs/STTNet/lib/python3.6/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/home/tianzhao.yang/anaconda3/envs/STTNet/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/tianzhao.yang/anaconda3/envs/STTNet/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/home/tianzhao.yang/anaconda3/envs/STTNet/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 79, in run
      _build_ext.run(self)
    File "/home/tianzhao.yang/anaconda3/envs/STTNet/lib/python3.6/distutils/command/build_ext.py", line 339, in run
      self.build_extensions()
    File "/home/tianzhao.yang/anaconda3/envs/STTNet/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 649, in build_extensions
      build_ext.build_extensions(self)
    File "/home/tianzhao.yang/anaconda3/envs/STTNet/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
      self._build_extensions_serial()
    File "/home/tianzhao.yang/anaconda3/envs/STTNet/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
      self.build_extension(ext)
    File "/home/tianzhao.yang/anaconda3/envs/STTNet/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 196, in build_extension
      _build_ext.build_extension(self, ext)
    File "/home/tianzhao.yang/anaconda3/envs/STTNet/lib/python3.6/distutils/command/build_ext.py", line 533, in build_extension
      depends=ext.depends)
    File "/home/tianzhao.yang/anaconda3/envs/STTNet/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 478, in unix_wrap_ninja_compile
      with_cuda=with_cuda)
    File "/home/tianzhao.yang/anaconda3/envs/STTNet/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1233, in _write_ninja_file_and_compile_objects
      error_prefix='Error compiling objects for extension')
    File "/home/tianzhao.yang/anaconda3/envs/STTNet/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1529, in _run_ninja_build
      raise RuntimeError(message)
  RuntimeError: Error compiling objects for extension
  ----------------------------------------
  ERROR: Failed building wheel for spatial-correlation-sampler

**Comment by ClementPinard** [comment]
the error you get is `nvcc fatal : Unsupported gpu architecture 'compute_75'`
What gpu are your tryng to install it on ? What driver and cuda version do you have ?
Does it still do the same if you are trying to build from source ?
