### ISSUE TITLE
failed to install spatial-correlation-sampler

### ISSUE THREAD

**Issue by z-fy-31** [ClementPinard/Pytorch-Correlation-extension#80]
Hi, my env is:
python 3.8
pytorch 1.8.0
cudatoolkit 11.1
torchvision 0.9.0
gcc 7.5.0

when i installed from source. there are following errors:

(pytorch1.8.0) zhengfangyuan@LX-SERVER:~/Pytorch-Correlation-extension-master/Pytorch-Correlation-extension-master$ pip list
Package           Version
----------------- ---------
certifi           2021.10.8
mkl-fft           1.3.1
mkl-random        1.2.2
mkl-service       2.4.0
numpy             1.21.2
olefile           0.46
Pillow            8.4.0
pip               21.2.4
setuptools        58.0.4
six               1.16.0
torch             1.8.0
torchvision       0.9.0
typing-extensions 3.10.0.2
wheel             0.37.0
(pytorch1.8.0) zhengfangyuan@LX-SERVER:~/Pytorch-Correlation-extension-master/Pytorch-Correlation-extension-master$ python setup.py install
running install
running bdist_egg
running egg_info
writing Correlation_Module/spatial_correlation_sampler.egg-info/PKG-INFO
writing dependency_links to Correlation_Module/spatial_correlation_sampler.egg-info/dependency_links.txt
writing requirements to Correlation_Module/spatial_correlation_sampler.egg-info/requires.txt
writing top-level names to Correlation_Module/spatial_correlation_sampler.egg-info/top_level.txt
reading manifest file 'Correlation_Module/spatial_correlation_sampler.egg-info/SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'Correlation_Module/spatial_correlation_sampler.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
building 'spatial_correlation_sampler_backend' extension
Emitting ninja build file /home/hdd1/zhengfangyuan/Pytorch-Correlation-extension-master/Pytorch-Correlation-extension-master/build/temp.linux-x86_64-3.8/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/3] :/home/hdd1/zhengfangyuan/cuda-11.1/bin/nvcc --generate-dependencies-with-compile --dependency-output /home/hdd1/zhengfangyuan/Pytorch-Correlation-extension-master/Pytorch-Correlation-extension-master/build/temp.linux-x86_64-3.8/Correlation_Module/correlation_cuda_kernel.o.d -DUSE_CUDA -I/home/hdd1/zhengfangyuan/anaconda3/envs/pytorch1.8.0/lib/python3.8/site-packages/torch/include -I/home/hdd1/zhengfangyuan/anaconda3/envs/pytorch1.8.0/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/hdd1/zhengfangyuan/anaconda3/envs/pytorch1.8.0/lib/python3.8/site-packages/torch/include/TH -I/home/hdd1/zhengfangyuan/anaconda3/envs/pytorch1.8.0/lib/python3.8/site-packages/torch/include/THC -I:/home/hdd1/zhengfangyuan/cuda-11.1/include -I/home/hdd1/zhengfangyuan/anaconda3/envs/pytorch1.8.0/include/python3.8 -c -c /home/hdd1/zhengfangyuan/Pytorch-Correlation-extension-master/Pytorch-Correlation-extension-master/Correlation_Module/correlation_cuda_kernel.cu -o /home/hdd1/zhengfangyuan/Pytorch-Correlation-extension-master/Pytorch-Correlation-extension-master/build/temp.linux-x86_64-3.8/Correlation_Module/correlation_cuda_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=spatial_correlation_sampler_backend -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 -std=c++14
FAILED: /home/hdd1/zhengfangyuan/Pytorch-Correlation-extension-master/Pytorch-Correlation-extension-master/build/temp.linux-x86_64-3.8/Correlation_Module/correlation_cuda_kernel.o
:/home/hdd1/zhengfangyuan/cuda-11.1/bin/nvcc --generate-dependencies-with-compile --dependency-output /home/hdd1/zhengfangyuan/Pytorch-Correlation-extension-master/Pytorch-Correlation-extension-master/build/temp.linux-x86_64-3.8/Correlation_Module/correlation_cuda_kernel.o.d -DUSE_CUDA -I/home/hdd1/zhengfangyuan/anaconda3/envs/pytorch1.8.0/lib/python3.8/site-packages/torch/include -I/home/hdd1/zhengfangyuan/anaconda3/envs/pytorch1.8.0/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/hdd1/zhengfangyuan/anaconda3/envs/pytorch1.8.0/lib/python3.8/site-packages/torch/include/TH -I/home/hdd1/zhengfangyuan/anaconda3/envs/pytorch1.8.0/lib/python3.8/site-packages/torch/include/THC -I:/home/hdd1/zhengfangyuan/cuda-11.1/include -I/home/hdd1/zhengfangyuan/anaconda3/envs/pytorch1.8.0/include/python3.8 -c -c /home/hdd1/zhengfangyuan/Pytorch-Correlation-extension-master/Pytorch-Correlation-extension-master/Correlation_Module/correlation_cuda_kernel.cu -o /home/hdd1/zhengfangyuan/Pytorch-Correlation-extension-master/Pytorch-Correlation-extension-master/build/temp.linux-x86_64-3.8/Correlation_Module/correlation_cuda_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=spatial_correlation_sampler_backend -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 -std=c++14
/bin/sh: 1: :/home/hdd1/zhengfangyuan/cuda-11.1/bin/nvcc: not found
[2/3] c++ -MMD -MF /home/hdd1/zhengfangyuan/Pytorch-Correlation-extension-master/Pytorch-Correlation-extension-master/build/temp.linux-x86_64-3.8/Correlation_Module/correlation_sampler.o.d -pthread -B /home/hdd1/zhengfangyuan/anaconda3/envs/pytorch1.8.0/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DUSE_CUDA -I/home/hdd1/zhengfangyuan/anaconda3/envs/pytorch1.8.0/lib/python3.8/site-packages/torch/include -I/home/hdd1/zhengfangyuan/anaconda3/envs/pytorch1.8.0/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/hdd1/zhengfangyuan/anaconda3/envs/pytorch1.8.0/lib/python3.8/site-packages/torch/include/TH -I/home/hdd1/zhengfangyuan/anaconda3/envs/pytorch1.8.0/lib/python3.8/site-packages/torch/include/THC -I:/home/hdd1/zhengfangyuan/cuda-11.1/include -I/home/hdd1/zhengfangyuan/anaconda3/envs/pytorch1.8.0/include/python3.8 -c -c /home/hdd1/zhengfangyuan/Pytorch-Correlation-extension-master/Pytorch-Correlation-extension-master/Correlation_Module/correlation_sampler.cpp -o /home/hdd1/zhengfangyuan/Pytorch-Correlation-extension-master/Pytorch-Correlation-extension-master/build/temp.linux-x86_64-3.8/Correlation_Module/correlation_sampler.o -fopenmp -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=spatial_correlation_sampler_backend -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
FAILED: /home/hdd1/zhengfangyuan/Pytorch-Correlation-extension-master/Pytorch-Correlation-extension-master/build/temp.linux-x86_64-3.8/Correlation_Module/correlation_sampler.o
c++ -MMD -MF /home/hdd1/zhengfangyuan/Pytorch-Correlation-extension-master/Pytorch-Correlation-extension-master/build/temp.linux-x86_64-3.8/Correlation_Module/correlation_sampler.o.d -pthread -B /home/hdd1/zhengfangyuan/anaconda3/envs/pytorch1.8.0/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DUSE_CUDA -I/home/hdd1/zhengfangyuan/anaconda3/envs/pytorch1.8.0/lib/python3.8/site-packages/torch/include -I/home/hdd1/zhengfangyuan/anaconda3/envs/pytorch1.8.0/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/hdd1/zhengfangyuan/anaconda3/envs/pytorch1.8.0/lib/python3.8/site-packages/torch/include/TH -I/home/hdd1/zhengfangyuan/anaconda3/envs/pytorch1.8.0/lib/python3.8/site-packages/torch/include/THC -I:/home/hdd1/zhengfangyuan/cuda-11.1/include -I/home/hdd1/zhengfangyuan/anaconda3/envs/pytorch1.8.0/include/python3.8 -c -c /home/hdd1/zhengfangyuan/Pytorch-Correlation-extension-master/Pytorch-Correlation-extension-master/Correlation_Module/correlation_sampler.cpp -o /home/hdd1/zhengfangyuan/Pytorch-Correlation-extension-master/Pytorch-Correlation-extension-master/build/temp.linux-x86_64-3.8/Correlation_Module/correlation_sampler.o -fopenmp -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=spatial_correlation_sampler_backend -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from /home/hdd1/zhengfangyuan/anaconda3/envs/pytorch1.8.0/lib/python3.8/site-packages/torch/include/c10/cuda/impl/CUDAGuardImpl.h:7:0,
                 from /home/hdd1/zhengfangyuan/anaconda3/envs/pytorch1.8.0/lib/python3.8/site-packages/torch/include/c10/cuda/CUDAGuard.h:3,
                 from /home/hdd1/zhengfangyuan/Pytorch-Correlation-extension-master/Pytorch-Correlation-extension-master/Correlation_Module/correlation_sampler.cpp:2:
/home/hdd1/zhengfangyuan/anaconda3/envs/pytorch1.8.0/lib/python3.8/site-packages/torch/include/c10/cuda/CUDAException.h:5:10: fatal error: cuda.h: No such file or directory
 #include <cuda.h>
          ^~~~~~~~
compilation terminated.
[3/3] c++ -MMD -MF /home/hdd1/zhengfangyuan/Pytorch-Correlation-extension-master/Pytorch-Correlation-extension-master/build/temp.linux-x86_64-3.8/Correlation_Module/correlation.o.d -pthread -B /home/hdd1/zhengfangyuan/anaconda3/envs/pytorch1.8.0/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DUSE_CUDA -I/home/hdd1/zhengfangyuan/anaconda3/envs/pytorch1.8.0/lib/python3.8/site-packages/torch/include -I/home/hdd1/zhengfangyuan/anaconda3/envs/pytorch1.8.0/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/hdd1/zhengfangyuan/anaconda3/envs/pytorch1.8.0/lib/python3.8/site-packages/torch/include/TH -I/home/hdd1/zhengfangyuan/anaconda3/envs/pytorch1.8.0/lib/python3.8/site-packages/torch/include/THC -I:/home/hdd1/zhengfangyuan/cuda-11.1/include -I/home/hdd1/zhengfangyuan/anaconda3/envs/pytorch1.8.0/include/python3.8 -c -c /home/hdd1/zhengfangyuan/Pytorch-Correlation-extension-master/Pytorch-Correlation-extension-master/Correlation_Module/correlation.cpp -o /home/hdd1/zhengfangyuan/Pytorch-Correlation-extension-master/Pytorch-Correlation-extension-master/build/temp.linux-x86_64-3.8/Correlation_Module/correlation.o -fopenmp -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=spatial_correlation_sampler_backend -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/hdd1/zhengfangyuan/anaconda3/envs/pytorch1.8.0/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1667, in _run_ninja_build
    subprocess.run(
  File "/home/hdd1/zhengfangyuan/anaconda3/envs/pytorch1.8.0/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "setup.py", line 57, in <module>
    launch_setup()
  File "setup.py", line 25, in launch_setup
    setup(
  File "/home/hdd1/zhengfangyuan/anaconda3/envs/pytorch1.8.0/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/hdd1/zhengfangyuan/anaconda3/envs/pytorch1.8.0/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/hdd1/zhengfangyuan/anaconda3/envs/pytorch1.8.0/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/hdd1/zhengfangyuan/anaconda3/envs/pytorch1.8.0/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/hdd1/zhengfangyuan/anaconda3/envs/pytorch1.8.0/lib/python3.8/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/home/hdd1/zhengfangyuan/anaconda3/envs/pytorch1.8.0/lib/python3.8/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/hdd1/zhengfangyuan/anaconda3/envs/pytorch1.8.0/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/hdd1/zhengfangyuan/anaconda3/envs/pytorch1.8.0/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/hdd1/zhengfangyuan/anaconda3/envs/pytorch1.8.0/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 164, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/hdd1/zhengfangyuan/anaconda3/envs/pytorch1.8.0/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 150, in call_command
    self.run_command(cmdname)
  File "/home/hdd1/zhengfangyuan/anaconda3/envs/pytorch1.8.0/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/hdd1/zhengfangyuan/anaconda3/envs/pytorch1.8.0/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/hdd1/zhengfangyuan/anaconda3/envs/pytorch1.8.0/lib/python3.8/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/home/hdd1/zhengfangyuan/anaconda3/envs/pytorch1.8.0/lib/python3.8/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/home/hdd1/zhengfangyuan/anaconda3/envs/pytorch1.8.0/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/hdd1/zhengfangyuan/anaconda3/envs/pytorch1.8.0/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/hdd1/zhengfangyuan/anaconda3/envs/pytorch1.8.0/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/home/hdd1/zhengfangyuan/anaconda3/envs/pytorch1.8.0/lib/python3.8/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/home/hdd1/zhengfangyuan/anaconda3/envs/pytorch1.8.0/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 708, in build_extensions
    build_ext.build_extensions(self)
  File "/home/hdd1/zhengfangyuan/anaconda3/envs/pytorch1.8.0/lib/python3.8/distutils/command/build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "/home/hdd1/zhengfangyuan/anaconda3/envs/pytorch1.8.0/lib/python3.8/distutils/command/build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/hdd1/zhengfangyuan/anaconda3/envs/pytorch1.8.0/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 202, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/hdd1/zhengfangyuan/anaconda3/envs/pytorch1.8.0/lib/python3.8/distutils/command/build_ext.py", line 528, in build_extension
    objects = self.compiler.compile(sources,
  File "/home/hdd1/zhengfangyuan/anaconda3/envs/pytorch1.8.0/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 529, in unix_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File "/home/hdd1/zhengfangyuan/anaconda3/envs/pytorch1.8.0/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1354, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
  File "/home/hdd1/zhengfangyuan/anaconda3/envs/pytorch1.8.0/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1683, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension

I hope I can get your help, Thanks!

**Comment by ClementPinard** [comment]
From your logs : `/bin/sh: 1: :/home/hdd1/zhengfangyuan/cuda-11.1/bin/nvcc: not found`

Apparently your CUDA environment cannot be found. Since it points to something else than `/usr/local/cuda`, I suppose you have set your environment variable `PATH`abd `LD_LIBRARY_PATH`. I guess the mose simple error you can search for is if cuda 11 is indeed in this very directory or not.

**Comment by z-fy-31** [comment]
> From your logs : `/bin/sh: 1: :/home/hdd1/zhengfangyuan/cuda-11.1/bin/nvcc: not found`
> 
> Apparently your CUDA environment cannot be found. Since it points to something else than `/usr/local/cuda`, I suppose you have set your environment variable `PATH`abd `LD_LIBRARY_PATH`. I guess the mose simple error you can search for is if cuda 11 is indeed in this very directory or not.

Thank you , I have found the problem ,  I set the wrong path of CUDA_HOME, now i successfully install spatial-correlation-sampler.

**Comment by 1212kyky** [comment]
**How to modify the wrong path of CUDA_HOME according to the error information?
Please give me some suggestions，thanks！！**

```
` ERROR: Command errored out with exit status 1:
   command: /home/cc/anaconda3/envs/ying/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-8jxokgji/spatial-correlation-sampler_71bd21056c914d5ab109c329ac6fb039/setup.py'"'"'; __file__='"'"'/tmp/pip-install-8jxokgji/spatial-correlation-sampler_71bd21056c914d5ab109c329ac6fb039/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-0jcndy7b
       cwd: /tmp/pip-install-8jxokgji/spatial-correlation-sampler_71bd21056c914d5ab109c329ac6fb039/
  Complete output (10 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  creating build/lib.linux-x86_64-3.6/spatial_correlation_sampler
  copying Correlation_Module/spatial_correlation_sampler/__init__.py -> build/lib.linux-x86_64-3.6/spatial_correlation_sampler
  copying Correlation_Module/spatial_correlation_sampler/spatial_correlation_sampler.py -> build/lib.linux-x86_64-3.6/spatial_correlation_sampler
  running build_ext
  error: [Errno 2] No such file or directory: '/usr/local/cuda/bin/nvcc/bin/nvcc': '/usr/local/cuda/bin/nvcc/bin/nvcc'
  ----------------------------------------
  ERROR: Failed building wheel for spatial-correlation-sampler`
```
