### ISSUE TITLE
Faile to install spatial-correlation-sampler

### ISSUE THREAD

**Issue by RongchangLi** [ClementPinard/Pytorch-Correlation-extension#83]
Hi, my env is:
python 3.8
pytorch 1.8.0
cudatoolkit 11.4
torchvision 0.9.0
gcc 9.3.0

I tried commands: pip install spatial-correlation-sampler
The result is:

```
(torch18) rongchang@BETA:~/extent_tools/Pytorch-Correlation-extension-master$ pip install spatial-correlation-sampler
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
WARNING: Keyring is skipped due to an exception: Failed to unlock the collection!
Collecting spatial-correlation-sampler
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/73/99/fbfcb914944c390e59aefd29c17fba2dd7d647a8b58385ca39ed0a32765f/spatial_correlation_sampler-0.3.0.tar.gz (8.6 kB)
Requirement already satisfied: torch>=1.1 in /data/Disk_A/rongchang/.local/lib/python3.8/site-packages (from spatial-correlation-sampler) (1.8.0+cu111)
Requirement already satisfied: numpy in /usr/local/anaconda3/lib/python3.8/site-packages (from spatial-correlation-sampler) (1.20.1)
Requirement already satisfied: typing-extensions in /usr/local/anaconda3/lib/python3.8/site-packages (from torch>=1.1->spatial-correlation-sampler) (3.7.4.3)
Building wheels for collected packages: spatial-correlation-sampler
  Building wheel for spatial-correlation-sampler (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/local/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-kcuopbgm/spatial-correlation-sampler_05a3547364fc43d4b8a1811af12f5d9f/setup.py'"'"'; __file__='"'"'/tmp/pip-install-kcuopbgm/spatial-correlation-sampler_05a3547364fc43d4b8a1811af12f5d9f/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-_np2padi
       cwd: /tmp/pip-install-kcuopbgm/spatial-correlation-sampler_05a3547364fc43d4b8a1811af12f5d9f/
  Complete output (54 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.8
  creating build/lib.linux-x86_64-3.8/spatial_correlation_sampler
  copying Correlation_Module/spatial_correlation_sampler/spatial_correlation_sampler.py -> build/lib.linux-x86_64-3.8/spatial_correlation_sampler
  copying Correlation_Module/spatial_correlation_sampler/__init__.py -> build/lib.linux-x86_64-3.8/spatial_correlation_sampler
  running build_ext
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-kcuopbgm/spatial-correlation-sampler_05a3547364fc43d4b8a1811af12f5d9f/setup.py", line 57, in <module>
      launch_setup()
    File "/tmp/pip-install-kcuopbgm/spatial-correlation-sampler_05a3547364fc43d4b8a1811af12f5d9f/setup.py", line 25, in launch_setup
      setup(
    File "/usr/local/anaconda3/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/usr/local/anaconda3/lib/python3.8/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/local/anaconda3/lib/python3.8/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/local/anaconda3/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/local/anaconda3/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/usr/local/anaconda3/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/anaconda3/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/local/anaconda3/lib/python3.8/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/local/anaconda3/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/anaconda3/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/local/anaconda3/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 79, in run
      _build_ext.run(self)
    File "/usr/local/anaconda3/lib/python3.8/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
      _build_ext.build_ext.run(self)
    File "/usr/local/anaconda3/lib/python3.8/distutils/command/build_ext.py", line 340, in run
      self.build_extensions()
    File "/data/Disk_A/rongchang/.local/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 378, in build_extensions
      self._check_abi()
    File "/data/Disk_A/rongchang/.local/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 734, in _check_abi
      check_compiler_abi_compatibility(compiler)
    File "/data/Disk_A/rongchang/.local/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 282, in check_compiler_abi_compatibility
      if not check_compiler_ok_for_platform(compiler):
    File "/data/Disk_A/rongchang/.local/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 242, in check_compiler_ok_for_platform
      which = subprocess.check_output(['which', compiler], stderr=subprocess.STDOUT)
    File "/usr/local/anaconda3/lib/python3.8/subprocess.py", line 415, in check_output
      return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
    File "/usr/local/anaconda3/lib/python3.8/subprocess.py", line 516, in run
      raise CalledProcessError(retcode, process.args,
  subprocess.CalledProcessError: Command '['which', 'g++']' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for spatial-correlation-sampler
  Running setup.py clean for spatial-correlation-sampler
Failed to build spatial-correlation-sampler
Installing collected packages: spatial-correlation-sampler
    Running setup.py install for spatial-correlation-sampler ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/local/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-kcuopbgm/spatial-correlation-sampler_05a3547364fc43d4b8a1811af12f5d9f/setup.py'"'"'; __file__='"'"'/tmp/pip-install-kcuopbgm/spatial-correlation-sampler_05a3547364fc43d4b8a1811af12f5d9f/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-bcf1fyrc/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /data/Disk_A/rongchang/.local/include/python3.8/spatial-correlation-sampler
         cwd: /tmp/pip-install-kcuopbgm/spatial-correlation-sampler_05a3547364fc43d4b8a1811af12f5d9f/
    Complete output (56 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.8
    creating build/lib.linux-x86_64-3.8/spatial_correlation_sampler
    copying Correlation_Module/spatial_correlation_sampler/spatial_correlation_sampler.py -> build/lib.linux-x86_64-3.8/spatial_correlation_sampler
    copying Correlation_Module/spatial_correlation_sampler/__init__.py -> build/lib.linux-x86_64-3.8/spatial_correlation_sampler
    running build_ext
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-kcuopbgm/spatial-correlation-sampler_05a3547364fc43d4b8a1811af12f5d9f/setup.py", line 57, in <module>
        launch_setup()
      File "/tmp/pip-install-kcuopbgm/spatial-correlation-sampler_05a3547364fc43d4b8a1811af12f5d9f/setup.py", line 25, in launch_setup
        setup(
      File "/usr/local/anaconda3/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/usr/local/anaconda3/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/anaconda3/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/local/anaconda3/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/local/anaconda3/lib/python3.8/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/local/anaconda3/lib/python3.8/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/usr/local/anaconda3/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/anaconda3/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/local/anaconda3/lib/python3.8/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/local/anaconda3/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/anaconda3/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/local/anaconda3/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 79, in run
        _build_ext.run(self)
      File "/usr/local/anaconda3/lib/python3.8/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
        _build_ext.build_ext.run(self)
      File "/usr/local/anaconda3/lib/python3.8/distutils/command/build_ext.py", line 340, in run
        self.build_extensions()
      File "/data/Disk_A/rongchang/.local/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 378, in build_extensions
        self._check_abi()
      File "/data/Disk_A/rongchang/.local/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 734, in _check_abi
        check_compiler_abi_compatibility(compiler)
      File "/data/Disk_A/rongchang/.local/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 282, in check_compiler_abi_compatibility
        if not check_compiler_ok_for_platform(compiler):
      File "/data/Disk_A/rongchang/.local/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 242, in check_compiler_ok_for_platform
        which = subprocess.check_output(['which', compiler], stderr=subprocess.STDOUT)
      File "/usr/local/anaconda3/lib/python3.8/subprocess.py", line 415, in check_output
        return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
      File "/usr/local/anaconda3/lib/python3.8/subprocess.py", line 516, in run
        raise CalledProcessError(retcode, process.args,
    subprocess.CalledProcessError: Command '['which', 'g++']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/local/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-kcuopbgm/spatial-correlation-sampler_05a3547364fc43d4b8a1811af12f5d9f/setup.py'"'"'; __file__='"'"'/tmp/pip-install-kcuopbgm/spatial-correlation-sampler_05a3547364fc43d4b8a1811af12f5d9f/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-bcf1fyrc/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /data/Disk_A/rongchang/.local/include/python3.8/spatial-correlation-sampler Check the logs for full command output.

```

I hope to use the caculation tool in my recent project. Can you please give some help ？Thanks!

**Comment by InnovArul** [comment]
> subprocess.CalledProcessError: Command '['which', 'g++']' returned non-zero exit status 1.

It seems `g++` is not installed? 
can you try installing it and then install this package by `pip install git+https://github.com/ClementPinard/Pytorch-Correlation-extension`?

**Comment by Lilaoxie** [comment]
> > subprocess.CalledProcessError: Command '['which', 'g++']' returned non-zero exit status 1.
> 
> It seems `g++` is not installed? can you try installing it and then install this package by `pip install git+https://github.com/ClementPinard/Pytorch-Correlation-extension`?

It works well! Thanks a lot!
