### ISSUE TITLE
python setup.py install failed

### ISSUE THREAD

**Issue by Onlyzdm** [ClementPinard/Pytorch-Correlation-extension#92]
![image](https://user-images.githubusercontent.com/51119756/226239252-98db17d0-f084-41b5-8b1e-c5de94d27f23.png)
torch = 1.7.1
cuda = 11.0
gcc = 7.5.0

(gar) lixu@icpc-SYS-4029GP-TRT:~/code/DFWSGAR-master/scripts/Pytorch-Correlation-extension-fix_1.7$ python setup.py install
running install
running bdist_egg
running egg_info
writing Correlation_Module/spatial_correlation_sampler.egg-info/PKG-INFO
writing dependency_links to Correlation_Module/spatial_correlation_sampler.egg-info/dependency_links.txt
writing requirements to Correlation_Module/spatial_correlation_sampler.egg-info/requires.txt
writing top-level names to Correlation_Module/spatial_correlation_sampler.egg-info/top_level.txt
reading manifest file 'Correlation_Module/spatial_correlation_sampler.egg-info/SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'Correlation_Module/spatial_correlation_sampler.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
building 'spatial_correlation_sampler_backend' extension
Emitting ninja build file /mnt/sdg/lixu/code/DFWSGAR-master/scripts/Pytorch-Correlation-extension-fix_1.7/build/temp.linux-x86_64-3.8/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/3] /usr/bin/nvcc -DUSE_CUDA -I/mnt/sdg/lixu/.conda/envs/gar/lib/python3.8/site-packages/torch/include -I/mnt/sdg/lixu/.conda/envs/gar/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/mnt/sdg/lixu/.conda/envs/gar/lib/python3.8/site-packages/torch/include/TH -I/mnt/sdg/lixu/.conda/envs/gar/lib/python3.8/site-packages/torch/include/THC -I/mnt/sdg/lixu/.conda/envs/gar/include/python3.8 -c -c /mnt/sdg/lixu/code/DFWSGAR-master/scripts/Pytorch-Correlation-extension-fix_1.7/Correlation_Module/correlation_cuda_kernel.cu -o /mnt/sdg/lixu/code/DFWSGAR-master/scripts/Pytorch-Correlation-extension-fix_1.7/build/temp.linux-x86_64-3.8/Correlation_Module/correlation_cuda_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=spatial_correlation_sampler_backend -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=sm_75 -std=c++14
FAILED: /mnt/sdg/lixu/code/DFWSGAR-master/scripts/Pytorch-Correlation-extension-fix_1.7/build/temp.linux-x86_64-3.8/Correlation_Module/correlation_cuda_kernel.o 
/usr/bin/nvcc -DUSE_CUDA -I/mnt/sdg/lixu/.conda/envs/gar/lib/python3.8/site-packages/torch/include -I/mnt/sdg/lixu/.conda/envs/gar/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/mnt/sdg/lixu/.conda/envs/gar/lib/python3.8/site-packages/torch/include/TH -I/mnt/sdg/lixu/.conda/envs/gar/lib/python3.8/site-packages/torch/include/THC -I/mnt/sdg/lixu/.conda/envs/gar/include/python3.8 -c -c /mnt/sdg/lixu/code/DFWSGAR-master/scripts/Pytorch-Correlation-extension-fix_1.7/Correlation_Module/correlation_cuda_kernel.cu -o /mnt/sdg/lixu/code/DFWSGAR-master/scripts/Pytorch-Correlation-extension-fix_1.7/build/temp.linux-x86_64-3.8/Correlation_Module/correlation_cuda_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=spatial_correlation_sampler_backend -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=sm_75 -std=c++14
nvcc fatal   : Unsupported gpu architecture 'compute_75'
[2/3] c++ -MMD -MF /mnt/sdg/lixu/code/DFWSGAR-master/scripts/Pytorch-Correlation-extension-fix_1.7/build/temp.linux-x86_64-3.8/Correlation_Module/correlation.o.d -pthread -B /mnt/sdg/lixu/.conda/envs/gar/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DUSE_CUDA -I/mnt/sdg/lixu/.conda/envs/gar/lib/python3.8/site-packages/torch/include -I/mnt/sdg/lixu/.conda/envs/gar/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/mnt/sdg/lixu/.conda/envs/gar/lib/python3.8/site-packages/torch/include/TH -I/mnt/sdg/lixu/.conda/envs/gar/lib/python3.8/site-packages/torch/include/THC -I/mnt/sdg/lixu/.conda/envs/gar/include/python3.8 -c -c /mnt/sdg/lixu/code/DFWSGAR-master/scripts/Pytorch-Correlation-extension-fix_1.7/Correlation_Module/correlation.cpp -o /mnt/sdg/lixu/code/DFWSGAR-master/scripts/Pytorch-Correlation-extension-fix_1.7/build/temp.linux-x86_64-3.8/Correlation_Module/correlation.o -fopenmp -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=spatial_correlation_sampler_backend -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
[3/3] c++ -MMD -MF /mnt/sdg/lixu/code/DFWSGAR-master/scripts/Pytorch-Correlation-extension-fix_1.7/build/temp.linux-x86_64-3.8/Correlation_Module/correlation_sampler.o.d -pthread -B /mnt/sdg/lixu/.conda/envs/gar/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DUSE_CUDA -I/mnt/sdg/lixu/.conda/envs/gar/lib/python3.8/site-packages/torch/include -I/mnt/sdg/lixu/.conda/envs/gar/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/mnt/sdg/lixu/.conda/envs/gar/lib/python3.8/site-packages/torch/include/TH -I/mnt/sdg/lixu/.conda/envs/gar/lib/python3.8/site-packages/torch/include/THC -I/mnt/sdg/lixu/.conda/envs/gar/include/python3.8 -c -c /mnt/sdg/lixu/code/DFWSGAR-master/scripts/Pytorch-Correlation-extension-fix_1.7/Correlation_Module/correlation_sampler.cpp -o /mnt/sdg/lixu/code/DFWSGAR-master/scripts/Pytorch-Correlation-extension-fix_1.7/build/temp.linux-x86_64-3.8/Correlation_Module/correlation_sampler.o -fopenmp -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=spatial_correlation_sampler_backend -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/mnt/sdg/lixu/.conda/envs/gar/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1533, in _run_ninja_build
    subprocess.run(
  File "/mnt/sdg/lixu/.conda/envs/gar/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "setup.py", line 57, in <module>
    launch_setup()
  File "setup.py", line 25, in launch_setup
    setup(
  File "/mnt/sdg/lixu/.conda/envs/gar/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/mnt/sdg/lixu/.conda/envs/gar/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/mnt/sdg/lixu/.conda/envs/gar/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/mnt/sdg/lixu/.conda/envs/gar/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/mnt/sdg/lixu/.conda/envs/gar/lib/python3.8/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/mnt/sdg/lixu/.conda/envs/gar/lib/python3.8/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/mnt/sdg/lixu/.conda/envs/gar/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/mnt/sdg/lixu/.conda/envs/gar/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/mnt/sdg/lixu/.conda/envs/gar/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 164, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/mnt/sdg/lixu/.conda/envs/gar/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 150, in call_command
    self.run_command(cmdname)
  File "/mnt/sdg/lixu/.conda/envs/gar/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/mnt/sdg/lixu/.conda/envs/gar/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/mnt/sdg/lixu/.conda/envs/gar/lib/python3.8/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/mnt/sdg/lixu/.conda/envs/gar/lib/python3.8/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/mnt/sdg/lixu/.conda/envs/gar/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/mnt/sdg/lixu/.conda/envs/gar/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/mnt/sdg/lixu/.conda/envs/gar/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/mnt/sdg/lixu/.conda/envs/gar/lib/python3.8/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/mnt/sdg/lixu/.conda/envs/gar/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 670, in build_extensions
    build_ext.build_extensions(self)
  File "/mnt/sdg/lixu/.conda/envs/gar/lib/python3.8/distutils/command/build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "/mnt/sdg/lixu/.conda/envs/gar/lib/python3.8/distutils/command/build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "/mnt/sdg/lixu/.conda/envs/gar/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 202, in build_extension
    _build_ext.build_extension(self, ext)
  File "/mnt/sdg/lixu/.conda/envs/gar/lib/python3.8/distutils/command/build_ext.py", line 528, in build_extension
    objects = self.compiler.compile(sources,
  File "/mnt/sdg/lixu/.conda/envs/gar/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 491, in unix_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File "/mnt/sdg/lixu/.conda/envs/gar/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1250, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
  File "/mnt/sdg/lixu/.conda/envs/gar/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1555, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension

**Comment by ClementPinard** [comment]
From your error message :

`nvcc fatal : Unsupported gpu architecture 'compute_75'`

Related issue :
https://github.com/torch/torch7/issues/1190

It seems related with your cuda version. People have this problem when the CUDA version is outdated. I am surprised this happens with CUDA 11.0; Can you check the nvcc version as well ? `nvcc --version` maybe this redirects to an older cuda version also installed in your system. in that case, you probably need to reset your `PATH` and `LD_LIBRARY_PATH` variables with the right paths. See https://docs.nvidia.com/cuda/cuda-installation-guide-linux/#environment-setup. notice the `cuda-{version}`, don't forget to put your version, i.e. `cuda-11`  or simply `cuda` if it's the latest installed cuda version.
