### ISSUE TITLE
Hello,I want to ask python setup.py install failed

### ISSUE THREAD

**Issue by Stitchsong** [ClementPinard/Pytorch-Correlation-extension#93]
running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-310
      creating build/lib.linux-x86_64-cpython-310/spatial_correlation_sampler
      copying Correlation_Module/spatial_correlation_sampler/__init__.py -> build/lib.linux-x86_64-cpython-310/spatial_correlation_sampler
      copying Correlation_Module/spatial_correlation_sampler/spatial_correlation_sampler.py -> build/lib.linux-x86_64-cpython-310/spatial_correlation_sampler
      running build_ext
      /root/anaconda3/envs/cma/lib/python3.10/site-packages/torch/utils/cpp_extension.py:813: UserWarning: The detected CUDA version (11.0) has a minor version mismatch with the version that was used to compile PyTorch (11.6). Most likely this shouldn't be a problem.
        warnings.warn(CUDA_MISMATCH_WARN.format(cuda_str_version, torch.version.cuda))
      /root/anaconda3/envs/cma/lib/python3.10/site-packages/torch/utils/cpp_extension.py:820: UserWarning: There are no g++ version bounds defined for CUDA version 11.0
        warnings.warn(f'There are no {compiler_name} version bounds defined for CUDA version {cuda_str_version}')
      building 'spatial_correlation_sampler_backend' extension
      creating /tmp/pip-install-2_mxhh4c/spatial-correlation-sampler_b99451c6c6e7484f9b11021c2edfa8fd/build/temp.linux-x86_64-cpython-310
      creating /tmp/pip-install-2_mxhh4c/spatial-correlation-sampler_b99451c6c6e7484f9b11021c2edfa8fd/build/temp.linux-x86_64-cpython-310/Correlation_Module
      Emitting ninja build file /tmp/pip-install-2_mxhh4c/spatial-correlation-sampler_b99451c6c6e7484f9b11021c2edfa8fd/build/temp.linux-x86_64-cpython-310/build.ninja...
      Compiling objects...
      Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
      [1/3] /usr/local/cuda/bin/nvcc  -DUSE_CUDA -I/root/anaconda3/envs/cma/lib/python3.10/site-packages/torch/include -I/root/anaconda3/envs/cma/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -I/root/anaconda3/envs/cma/lib/python3.10/site-packages/torch/include/TH -I/root/anaconda3/envs/cma/lib/python3.10/site-packages/torch/include/THC -I/usr/local/cuda/include -I/root/anaconda3/envs/cma/include/python3.10 -c -c /tmp/pip-install-2_mxhh4c/spatial-correlation-sampler_b99451c6c6e7484f9b11021c2edfa8fd/Correlation_Module/correlation_cuda_kernel.cu -o /tmp/pip-install-2_mxhh4c/spatial-correlation-sampler_b99451c6c6e7484f9b11021c2edfa8fd/build/temp.linux-x86_64-cpython-310/Correlation_Module/correlation_cuda_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1013"' -DTORCH_EXTENSION_NAME=spatial_correlation_sampler_backend -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 -std=c++14
      FAILED: /tmp/pip-install-2_mxhh4c/spatial-correlation-sampler_b99451c6c6e7484f9b11021c2edfa8fd/build/temp.linux-x86_64-cpython-310/Correlation_Module/correlation_cuda_kernel.o
      /usr/local/cuda/bin/nvcc  -DUSE_CUDA -I/root/anaconda3/envs/cma/lib/python3.10/site-packages/torch/include -I/root/anaconda3/envs/cma/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -I/root/anaconda3/envs/cma/lib/python3.10/site-packages/torch/include/TH -I/root/anaconda3/envs/cma/lib/python3.10/site-packages/torch/include/THC -I/usr/local/cuda/include -I/root/anaconda3/envs/cma/include/python3.10 -c -c /tmp/pip-install-2_mxhh4c/spatial-correlation-sampler_b99451c6c6e7484f9b11021c2edfa8fd/Correlation_Module/correlation_cuda_kernel.cu -o /tmp/pip-install-2_mxhh4c/spatial-correlation-sampler_b99451c6c6e7484f9b11021c2edfa8fd/build/temp.linux-x86_64-cpython-310/Correlation_Module/correlation_cuda_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1013"' -DTORCH_EXTENSION_NAME=spatial_correlation_sampler_backend -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 -std=c++14
      nvcc fatal   : Unsupported gpu architecture 'compute_86'
      [2/3] c++ -MMD -MF /tmp/pip-install-2_mxhh4c/spatial-correlation-sampler_b99451c6c6e7484f9b11021c2edfa8fd/build/temp.linux-x86_64-cpython-310/Correlation_Module/correlation_sampler.o.d -pthread -B /root/anaconda3/envs/cma/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -fPIC -O2 -isystem /root/anaconda3/envs/cma/include -fPIC -O2 -isystem /root/anaconda3/envs/cma/include -fPIC -DUSE_CUDA -I/root/anaconda3/envs/cma/lib/python3.10/site-packages/torch/include -I/root/anaconda3/envs/cma/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -I/root/anaconda3/envs/cma/lib/python3.10/site-packages/torch/include/TH -I/root/anaconda3/envs/cma/lib/python3.10/site-packages/torch/include/THC -I/usr/local/cuda/include -I/root/anaconda3/envs/cma/include/python3.10 -c -c /tmp/pip-install-2_mxhh4c/spatial-correlation-sampler_b99451c6c6e7484f9b11021c2edfa8fd/Correlation_Module/correlation_sampler.cpp -o /tmp/pip-install-2_mxhh4c/spatial-correlation-sampler_b99451c6c6e7484f9b11021c2edfa8fd/build/temp.linux-x86_64-cpython-310/Correlation_Module/correlation_sampler.o -fopenmp -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1013"' -DTORCH_EXTENSION_NAME=spatial_correlation_sampler_backend -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
      [3/3] c++ -MMD -MF /tmp/pip-install-2_mxhh4c/spatial-correlation-sampler_b99451c6c6e7484f9b11021c2edfa8fd/build/temp.linux-x86_64-cpython-310/Correlation_Module/correlation.o.d -pthread -B /root/anaconda3/envs/cma/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -fPIC -O2 -isystem /root/anaconda3/envs/cma/include -fPIC -O2 -isystem /root/anaconda3/envs/cma/include -fPIC -DUSE_CUDA -I/root/anaconda3/envs/cma/lib/python3.10/site-packages/torch/include -I/root/anaconda3/envs/cma/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -I/root/anaconda3/envs/cma/lib/python3.10/site-packages/torch/include/TH -I/root/anaconda3/envs/cma/lib/python3.10/site-packages/torch/include/THC -I/usr/local/cuda/include -I/root/anaconda3/envs/cma/include/python3.10 -c -c /tmp/pip-install-2_mxhh4c/spatial-correlation-sampler_b99451c6c6e7484f9b11021c2edfa8fd/Correlation_Module/correlation.cpp -o /tmp/pip-install-2_mxhh4c/spatial-correlation-sampler_b99451c6c6e7484f9b11021c2edfa8fd/build/temp.linux-x86_64-cpython-310/Correlation_Module/correlation.o -fopenmp -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1013"' -DTORCH_EXTENSION_NAME=spatial_correlation_sampler_backend -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
      ninja: build stopped: subcommand failed.
      Traceback (most recent call last):
        File "/root/anaconda3/envs/cma/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1808, in _run_ninja_build
          subprocess.run(
        File "/root/anaconda3/envs/cma/lib/python3.10/subprocess.py", line 524, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
      
      The above exception was the direct cause of the following exception:
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-2_mxhh4c/spatial-correlation-sampler_b99451c6c6e7484f9b11021c2edfa8fd/setup.py", line 57, in <module>
          launch_setup()
        File "/tmp/pip-install-2_mxhh4c/spatial-correlation-sampler_b99451c6c6e7484f9b11021c2edfa8fd/setup.py", line 25, in launch_setup
          setup(
        File "/root/anaconda3/envs/cma/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/root/anaconda3/envs/cma/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/root/anaconda3/envs/cma/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/root/anaconda3/envs/cma/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/root/anaconda3/envs/cma/lib/python3.10/site-packages/setuptools/dist.py", line 1208, in run_command
          super().run_command(command)
        File "/root/anaconda3/envs/cma/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/root/anaconda3/envs/cma/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 325, in run
          self.run_command("build")
        File "/root/anaconda3/envs/cma/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/root/anaconda3/envs/cma/lib/python3.10/site-packages/setuptools/dist.py", line 1208, in run_command
          super().run_command(command)
        File "/root/anaconda3/envs/cma/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/root/anaconda3/envs/cma/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 132, in run
          self.run_command(cmd_name)
        File "/root/anaconda3/envs/cma/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/root/anaconda3/envs/cma/lib/python3.10/site-packages/setuptools/dist.py", line 1208, in run_command
          super().run_command(command)
        File "/root/anaconda3/envs/cma/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/root/anaconda3/envs/cma/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 84, in run
          _build_ext.run(self)
        File "/root/anaconda3/envs/cma/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 346, in run
          self.build_extensions()
        File "/root/anaconda3/envs/cma/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 765, in build_extensions
          build_ext.build_extensions(self)
        File "/root/anaconda3/envs/cma/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 468, in build_extensions
          self._build_extensions_serial()
        File "/root/anaconda3/envs/cma/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 494, in _build_extensions_serial
          self.build_extension(ext)
        File "/root/anaconda3/envs/cma/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 246, in build_extension
          _build_ext.build_extension(self, ext)
        File "/root/anaconda3/envs/cma/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 549, in build_extension
          objects = self.compiler.compile(
        File "/root/anaconda3/envs/cma/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 586, in unix_wrap_ninja_compile
          _write_ninja_file_and_compile_objects(
        File "/root/anaconda3/envs/cma/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1487, in _write_ninja_file_and_compile_objects
          _run_ninja_build(
        File "/root/anaconda3/envs/cma/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1824, in _run_ninja_build
          raise RuntimeError(message) from e
      RuntimeError: Error compiling objects for extension

**Comment by Stitchsong** [comment]
my cuda version is 11.4 
gcc version is 7.5.0 
I have tried the torch==1.11.0+cu113 and the 1.12.0+cu116 but all failed, I want to ask you about how to fix it.

**Comment by ClementPinard** [comment]
The error is 
```
nvcc fatal : Unsupported gpu architecture 'compute_86'
```

Normally, this problem is related to Cuda 10 and lower version, which are not compatible with the last GPUs. It's strange because you said your cuda version was 11.4, which is normally compatible with architecture 86.

See https://docs.nvidia.com/cuda/ada-compatibility-guide/index.html#building-applications-using-cuda-toolkit-11-0-through-11-7

So I suspect the nvcc is not the right one. What is the output of `nvcc --version` ?

**Comment by Stitchsong** [comment]
Thank you so much, it is actually my nvcc has a problem and I have solved it. 
Best wishes to you
